version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: arunagn
  MYSQL_PASSWORD:
  MYSQL_DATABASE: react-wallet

services:
  mysql:
    image: mysql:8.0.21
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD:
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
  server:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mysql
    expose:
      - 5000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    links:
      - mysql
    command: npm start
