version: "3.4"

services:
  db:
    image: mysql:8.0.21
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 6
      start_period: 0s
    ports:
      - 3306:3306
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
  server:
    build: .
    restart: always
    environment:
      MYSQL_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5000:5000
    external_links:
      - db
